spring:

  application:
    name: ProjetoAvancadaWeb

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://172.23.71.93:5432/AvancadaWeb
    username: postgres
    password: root

    hikari:
      maximum-pool-size: 10 # Número máximo de conexões no pool
      minimum-idle: 5 # Mínimo de conexões ociosas
      idle-timeout: 600000 # Tempo máximo que uma conexão pode ficar ociosa (10 minutos)
      max-lifetime: 1800000 # Tempo máximo de vida de uma conexão (30 minutos)
      connection-timeout: 30000 # Tempo máximo para tentar obter uma conexão (30 segundos)
      validation-timeout: 5000 # Tempo máximo para validar uma conexão (5 segundos)
      connection-test-query: "SELECT 1" # Consulta para validar conexões

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

jwt:
  secret-key: ${secret-key}   # Uma chave secreta forte, use pelo menos 256 bits
  issuer: "ProjetoAvancadaWeb"
springdoc:
  swagger-ui:
    path: /gestao-requisicoes.html

  api-docs:
    path: /gestao-requisicoes

  packages-to-scan: com.example.projetoavancadaweb.web.controller

